name: z55250825
url: http://s.pacn.ws/1500/84/pa.146000.2.jpg?o3lazg
description: 一只蒟蒻

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
