name: z55250825
url: https://img1.doubanio.com/lpic/s4132473.jpg
description: 一只蒟蒻

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
